server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive  # ✅ Important: use WebFlux
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE   #lb - loadbalance
              predicates:
                - Path=/users/**

            - id: HOTEL-SERVICE
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotels/**

            - id: ratingservice
              uri: lb://ratingservice
              predicates:
                - Path=/ratings/**
