server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive  # Important: use WebFlux
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE   #lb - loadbalance
              predicates:
                - Path=/users/**

            - id: HOTEL-SERVICE
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotels/**

            - id: ratingservice
              uri: lb://ratingservice
              predicates:
                - Path=/ratings/**

#Okta configuration for api gateway
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oavmgbzcb6fwz7kx697
            client-secret: KDXMkwmZDcimw5PNbAujTYGf4OdPyolEwjprk_6aCoiAjJXmnodAgklFuXRHbXst
            scope: openid, profile, email, offline_access
            provider: okta
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          okta:
            issuer-uri: https://integrator-8582351.okta.com/oauth2/default
      resourceserver:
          jwt:
            jwk-set-uri: https://integrator-8582351.okta.com/oauth2/default